# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Increment version"
  lane :increment_build_versioncode do
    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/
    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s
    f = File.new(path, 'w')
    f.write(s)
    f.close
    end

  desc "Build Apk"
    lane :build do
      increment_build_versioncode
      gradle(task: "clean")
      gradle(
          task: "bundle",
          build_type: 'Release'
        )
      end

  desc "Deploy firebase distribute"
    lane :distribute do |options|
      firebase_app_distribution(
          app: "<your app>",
          release_notes_file: "../release-notes.txt",
          groups: "<your team>",
          apk_path: "../build/app/outputs/apk/release/app-release.apk"
          # firebase_cli_path: "/usr/local/bin/firebase",
      )
    end
end
